data_folder:

# Data
kspace_shape: [320, 320]
acceleration_factor: 8
data_mean: 0.0001204
data_std: 0.000118

# Training
epochs: 10000
batch_size: 1
lr: 1e-4
device: cuda
verbose: 100
seed: 3 # for reproducibility
restore:
min_loss: 0.01

# Model
model:
  dim_bottleneck: 64
  conv_channels: 64

res_dir: